In [1]:
!pip install kaggle pandas numpy matplotlib seaborn scikit-learn shap


In [2]:
from google.colab import files
uploaded = files.upload()


Saving WA_Fn-UseC_-Telco-Customer-Churn.csv to WA_Fn-UseC_-Telco-Customer-Churn.csv


In [3]:
import pandas as pd

df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()


customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [4]:
# Check missing values
df.isnull().sum()

# Convert TotalCharges to numeric (some values might be empty strings)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Drop missing values
df = df.dropna()

# Drop customerID (not a useful feature)
df = df.drop('customerID', axis=1)




In [5]:
df.head(10)

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   
5  Female              0      No         No       8          Yes   
6    Male              0      No        Yes      22          Yes   
7  Female              0      No         No      10           No   
8  Female              0     Yes         No      28          Yes   
9    Male              0      No        Yes      62          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   
5               Yes     Fiber optic             No           No   
6               Yes     Fiber optic             No          Yes   
7  No phone service             DSL            Yes           No   
8               Yes     Fiber optic             No           No   
9                No             DSL            Yes          Yes   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   
5              Yes          No         Yes             Yes  Month-to-month   
6               No          No         Yes              No  Month-to-month   
7               No          No          No              No  Month-to-month   
8              Yes         Yes         Yes             Yes  Month-to-month   
9               No          No          No              No        One year   

  PaperlessBilling              PaymentMethod  MonthlyCharges  TotalCharges  \
0              Yes           Electronic check           29.85         29.85   
1               No               Mailed check           56.95       1889.50   
2              Yes               Mailed check           53.85        108.15   
3               No  Bank transfer (automatic)           42.30       1840.75   
4              Yes           Electronic check           70.70        151.65   
5              Yes           Electronic check           99.65        820.50   
6              Yes    Credit card (automatic)           89.10       1949.40   
7               No               Mailed check           29.75        301.90   
8              Yes           Electronic check          104.80       3046.05   
9               No  Bank transfer (automatic)           56.15       3487.95   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes  
5   Yes  
6    No  
7    No  
8   Yes  
9    No

In [6]:
binary_map = {
    'Yes': 1,
    'No': 0,
    'No internet service': 0,
    'No phone service': 0
}

# Columns to apply this mapping
binary_columns = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'Churn',
                  'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
                  'StreamingTV', 'StreamingMovies', 'MultipleLines']

for col in binary_columns:
    df[col] = df[col].replace(binary_map)

# Gender column: manually map Male/Female
df['gender'] = df['gender'].map({'Female': 0, 'Male': 1})


<ipython-input-6-8bdff030c38d>:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].replace(binary_map)


In [7]:
df.head(100)

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0        0              0        1           0       1             0   
1        1              0        0           0      34             1   
2        1              0        0           0       2             1   
3        1              0        0           0      45             0   
4        0              0        0           0       2             1   
..     ...            ...      ...         ...     ...           ...   
95       0              0        0           0      12             1   
96       1              0        1           1      71             1   
97       1              0        0           0       5             1   
98       1              0        0           0      52             1   
99       0              1        1           0      25             1   

    MultipleLines InternetService  OnlineSecurity  OnlineBackup  \
0               0             DSL               0             1   
1               0             DSL               1             0   
2               0             DSL               1             1   
3               0             DSL               1             0   
4               0     Fiber optic               0             0   
..            ...             ...             ...           ...   
95              1     Fiber optic               1             0   
96              1             DSL               1             1   
97              0              No               0             0   
98              0              No               0             0   
99              0     Fiber optic               0             1   

    DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
0                  0            0            0                0   
1                  1            0            0                0   
2                  0            0            0                0   
3                  1            1            0                0   
4                  0            0            0                0   
..               ...          ...          ...              ...   
95                 0            0            0                0   
96                 0            1            0                0   
97                 0            0            0                0   
98                 0            0            0                0   
99                 1            0            1                1   

          Contract  PaperlessBilling              PaymentMethod  \
0   Month-to-month                 1           Electronic check   
1         One year                 0               Mailed check   
2   Month-to-month                 1               Mailed check   
3         One year                 0  Bank transfer (automatic)   
4   Month-to-month                 1           Electronic check   
..             ...               ...                        ...   
95  Month-to-month                 1           Electronic check   
96        One year                 1    Credit card (automatic)   
97  Month-to-month                 0               Mailed check   
98        Two year                 0  Bank transfer (automatic)   
99  Month-to-month                 1           Electronic check   

    MonthlyCharges  TotalCharges  Churn  
0            29.85         29.85      0  
1            56.95       1889.50      0  
2            53.85        108.15      1  
3            42.30       1840.75      0  
4            70.70        151.65      1  
..             ...           ...    ...  
95           78.95        927.35      1  
96           66.85       4748.70      0  
97           21.05        113.85      1  
98           21.00       1107.20      0  
99           98.50       2514.50      1  

[100 rows x 20 columns]

In [8]:
# Manual encoding of InternetService
df['InternetService'] = df['InternetService'].map({
    'No': 0,
    'DSL': 1,
    'Fiber optic': 2
})

# Manual encoding of Contract
df['Contract'] = df['Contract'].map({
    'Month-to-month': 0,
    'One year': 1,
    'Two year': 2
})

# Manual encoding of PaymentMethod
df['PaymentMethod'] = df['PaymentMethod'].map({
    'Credit card (automatic)': 0,
    'Electronic check': 1,
    'Mailed check': 2,
    'Bank transfer (automatic)': 3
})


In [9]:
# Check if conversion worked
print(df['InternetService'].unique())
print(df['Contract'].unique())
print(df['PaymentMethod'].unique())


[1 2 0]
[0 1 2]
[1 2 3 0]


In [10]:
df.head(10)

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0   
1       1              0        0           0      34             1   
2       1              0        0           0       2             1   
3       1              0        0           0      45             0   
4       0              0        0           0       2             1   
5       0              0        0           0       8             1   
6       1              0        0           1      22             1   
7       0              0        0           0      10             0   
8       0              0        1           0      28             1   
9       1              0        0           1      62             1   

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0              0                1               0             1   
1              0                1               1             0   
2              0                1               1             1   
3              0                1               1             0   
4              0                2               0             0   
5              1                2               0             0   
6              1                2               0             1   
7              0                1               1             0   
8              1                2               0             0   
9              0                1               1             1   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 0            0            0                0         0   
1                 1            0            0                0         1   
2                 0            0            0                0         0   
3                 1            1            0                0         1   
4                 0            0            0                0         0   
5                 1            0            1                1         0   
6                 0            0            1                0         0   
7                 0            0            0                0         0   
8                 1            1            1                1         0   
9                 0            0            0                0         1   

   PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0                 1              1           29.85         29.85      0  
1                 0              2           56.95       1889.50      0  
2                 1              2           53.85        108.15      1  
3                 0              3           42.30       1840.75      0  
4                 1              1           70.70        151.65      1  
5                 1              1           99.65        820.50      1  
6                 1              0           89.10       1949.40      0  
7                 0              2           29.75        301.90      0  
8                 1              1          104.80       3046.05      1  
9                 0              3           56.15       3487.95      0

In [14]:
# Define target and features
X = df.drop('Churn', axis=1)
y = df['Churn']


In [12]:
y_pred = rf_model.predict(X_test)


NameError: name 'rf_model' is not defined

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
# 80% training, 20% testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


# Create model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train
rf_model.fit(X_train, y_train)
print("Accuracy:", accuracy_score(y_test, y_pred))
# Confusion matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Classification report
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Accuracy



NameError: name 'y_pred' is not defined

In [15]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score

# Step 1: Split data into features and target
X = df.drop('Churn', axis=1)
y = df['Churn']

# Step 2: Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Step 3: Create and train SVM model
svm_model = SVC(kernel='rbf', probability=True, random_state=42)
svm_model.fit(X_train, y_train)

# Step 4: Predict
y_pred = svm_model.predict(X_test)
y_proba = svm_model.predict_proba(X_test)[:, 1]

# Step 5: Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("ROC AUC Score:", roc_auc_score(y_test, y_proba))


Accuracy: 0.7341862117981521

Confusion Matrix:
 [[1033    0]
 [ 374    0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.73      1.00      0.85      1033
           1       0.00      0.00      0.00       374

    accuracy                           0.73      1407
   macro avg       0.37      0.50      0.42      1407
weighted avg       0.54      0.73      0.62      1407

ROC AUC Score: 0.7876311661688349


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score

# Step 1: Split data into features and target
X = df.drop('Churn', axis=1)
y = df['Churn']

# Step 2: Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Step 3: Create and train Logistic Regression model
log_model = LogisticRegression(max_iter=1000, random_state=42)
log_model.fit(X_train, y_train)

# Step 4: Predict
y_pred = log_model.predict(X_test)
y_proba = log_model.predict_proba(X_test)[:, 1]

# Step 5: Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("ROC AUC Score:", roc_auc_score(y_test, y_proba))


Accuracy: 0.7903340440653873

Confusion Matrix:
 [[903 130]
 [165 209]]

Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.87      0.86      1033
           1       0.62      0.56      0.59       374

    accuracy                           0.79      1407
   macro avg       0.73      0.72      0.72      1407
weighted avg       0.78      0.79      0.79      1407

ROC AUC Score: 0.8334571441883099


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [17]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score

# Step 1: Define features and target
X = df.drop('Churn', axis=1)
y = df['Churn']

# Step 2: Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Step 3: Train XGBoost model
xgb_model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=4,
    use_label_encoder=False,
    eval_metric='logloss',
    random_state=42
)

xgb_model.fit(X_train, y_train)

# Step 4: Predict
y_pred = xgb_model.predict(X_test)
y_proba = xgb_model.predict_proba(X_test)[:, 1]

# Step 5: Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("ROC AUC Score:", roc_auc_score(y_test, y_proba))
import pickle

# Save the trained XGBoost model to a file
with open("xgb_churn_model.pkl", "wb") as f:
    pickle.dump(xgb_model, f)

print("✅ Model saved as xgb_churn_model.pkl")


/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [04:16:54] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Accuracy: 0.7910447761194029

Confusion Matrix:
 [[909 124]
 [170 204]]

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.88      0.86      1033
           1       0.62      0.55      0.58       374

    accuracy                           0.79      1407
   macro avg       0.73      0.71      0.72      1407
weighted avg       0.78      0.79      0.79      1407

ROC AUC Score: 0.8352690103586978
✅ Model saved as xgb_churn_model.pkl
